version: 2
jobs:
  build:

    working_directory: ~/quantal_users

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: quantal_users-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - run: mkdir -p /var/log
      - run: sudo touch /var/log/springboot_log.log /var/log/app_log.log /var/log/app_log.json && sudo chmod 777 /var/log/springboot_log.log /var/log/app_log.log /var/log/app_log.json

      - save_cache:
          paths:
            - ~/.m2
          key: quantal_users-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/quantal_users-0.0.1-SNAPSHOT.jar
