version: '2'
services:

  quantalex_users:
    build:
      context: ./../../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres_quantal_users
      - DB_PORT=5432
    links:
      - postgres_quantal_users
    depends_on:
      - postgres_quantal_users
    command: ["/wait-for-it.sh", "postgres_quantal_users:5432", "--", "java",  "-jar", "~/quantalex-users-0.0.1-SNAPSHOT.jar"]

  # The postgres database
  postgres_quantal_users:
    restart: always
    image: sameersbn/postgresql:9.6-2
    ports:
      - "5433:5432"
    environment:
      - DEBUG=false
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=quantal_exchange_users
      - PG_PASSWORD=postgres
      - DB_TEMPLATE=

      - DB_EXTENSION=

      - REPLICATION_MODE=
      - REPLICATION_USER=
      - REPLICATION_PASS=
      - REPLICATION_SSLMODE=
    volumes:
      - /private/var/docker/postgresql/quantalex_users:/var/lib/postgresql
